export const LOADING_DATA = 'APP/LOADING_DATA'
export const ON_ADD_FORM = 'APP/ON_ADD_FORM'
export const OFF_ADD_FORM = 'APP/OFF_ADD_FORM'
export const ON_EDIT_FORM = 'APP/ON_EDIT_FORM'
export const OFF_EDIT_FORM = 'APP/OFF_EDIT_FORM'